export enum DecisionType {
  NONE = 0,
  PASS = 1,
  CROSS = 2,
  SHOT = 3,
  DRIBBLE = 4,
  HOLD_BALL = 5,
  CLEAR = 6,
  RECEIVE = 7,
  HEADER = 8,
  CONTROL = 9,
  SKILL_MOVE = 10,
  MOVE = 11,
  MARK = 12,
  COVER = 13,
  PRESS = 14,
  INTERCEPT = 15,
  TACKLE = 16,
  BLOCK = 17,
  POSITION = 18,
  SET_PIECE = 19,
  GK_CLAIM = 20,
  GK_DISTRIBUTE = 21,
  FAKE = 22,
  TACTICAL_FOUL = 23,
}
