import { useMemo, useState } from "react";
import type { MatchSnapshot } from "../simulation/types";
import type { CommunicationHealth, DebugAlert, DebugLevel, MatchStateAdapter, RawNetworkSnapshot, ReconciliationRow, RetentionMode } from "../debug/observability";

const TABS=["Resumo","Estatísticas","Jogadores","Eventos","Timeline","Posse","Chutes e xG","Engine x Front","Sincronização","Alertas","Estado bruto","Configuração"] as const;
type Tab=typeof TABS[number];

interface Props{
  raw:RawNetworkSnapshot|null; snapshot:MatchSnapshot; health:CommunicationHealth; alerts:readonly DebugAlert[];
  renderedState:{players:Readonly<Record<string,{x:number;y:number}>>;ball:{x:number;y:number};capturedAt:number};
  reconciliation:readonly ReconciliationRow[]; adapter:MatchStateAdapter; selectedPlayerId:string|null;
  onSelectPlayer:(id:string|null)=>void; rendererFrozen:boolean; onRendererFrozen:(value:boolean)=>void;
  debugLevel:DebugLevel; onDebugLevel:(value:DebugLevel)=>void; retention:RetentionMode; onRetention:(value:RetentionMode)=>void;
  onStep:()=>void;
}

export function DebugPanel(props:Props){
  const [tab,setTab]=useState<Tab>("Resumo");
  const [eventFilter,setEventFilter]=useState("");
  const [expandedEvent,setExpandedEvent]=useState<number|null>(null);
  const selected=props.snapshot.players.find(player=>player.id===props.selectedPlayerId)??null;
  const events=useMemo(()=>props.adapter.retainedEvents().filter(event=>!eventFilter||event.type.includes(eventFilter.toUpperCase())||event.playerId?.includes(eventFilter)),[props.adapter,props.raw,eventFilter]);
  if(props.debugLevel==="OFF")return <section className="debug-disabled"><b>Debug desativado.</b><button onClick={()=>props.onDebugLevel("BASIC")}>Ativar</button></section>;
  return <section className="debug-panel">
    <div className="debug-heading"><div><p className="eyebrow">Observabilidade causal</p><h2>Painel Engine ↔ Frontend</h2></div><HealthBadge health={props.health}/></div>
    <nav className="debug-tabs">{TABS.map(value=><button key={value} className={tab===value?"active":""} onClick={()=>setTab(value)}>{value}</button>)}</nav>
    <div className="debug-content">
      {tab==="Resumo"&&<Summary {...props}/>} 
      {tab==="Estatísticas"&&<Statistics raw={props.raw} reconciliation={props.reconciliation}/>} 
      {tab==="Jogadores"&&<Players raw={props.raw} snapshot={props.snapshot} selectedId={props.selectedPlayerId} onSelect={props.onSelectPlayer} selected={selected}/>} 
      {tab==="Eventos"&&<div><input className="debug-filter" value={eventFilter} onChange={event=>setEventFilter(event.target.value)} placeholder="Filtrar tipo ou jogador"/><div className="event-table">{events.slice(-250).reverse().map(event=><div key={event.sequence} className="event-row" onClick={()=>setExpandedEvent(expandedEvent===event.sequence?null:event.sequence)}><b>#{event.sequence}</b><span>{formatClock(event.simulationTimeMs/1000)}</span><strong>{event.type}</strong><span>{event.teamId??"—"}</span><span>{event.playerId??"—"}</span>{expandedEvent===event.sequence&&<pre>{JSON.stringify(event,null,2)}</pre>}</div>)}</div></div>}
      {tab==="Timeline"&&<div className="timeline-debug">{props.snapshot.timeline?.slice().reverse().map(entry=><div key={entry.eventId}><b>{entry.minute}'</b><span>{entry.label}</span></div>)}</div>}
      {tab==="Posse"&&<Possession raw={props.raw} snapshot={props.snapshot}/>} 
      {tab==="Chutes e xG"&&<Shots raw={props.raw}/>} 
      {tab==="Engine x Front"&&<EngineFront raw={props.raw} snapshot={props.snapshot} renderedState={props.renderedState}/>} 
      {tab==="Sincronização"&&<Synchronization adapter={props.adapter} health={props.health} reconciliation={props.reconciliation} rendererFrozen={props.rendererFrozen} onRendererFrozen={props.onRendererFrozen} onStep={props.onStep}/>} 
      {tab==="Alertas"&&<Alerts alerts={props.alerts}/>} 
      {tab==="Estado bruto"&&<pre className="raw-state">{JSON.stringify(props.raw,null,2)}</pre>}
      {tab==="Configuração"&&<Configuration {...props}/>} 
    </div>
  </section>;
}

function Summary({raw,snapshot,health,alerts,reconciliation}:Props){
  return <div className="debug-grid"><Card title="Partida"><Metric label="Seed" value={raw?.seed}/><Metric label="Tick" value={raw?.simulationTick}/><Metric label="Tempo" value={formatClock(snapshot.time)}/><Metric label="Fase" value={snapshot.phase}/><Metric label="Posse" value={raw?.possessionTeamId??"disputada"}/></Card><Card title="Placar oficial"><div className="debug-score">{snapshot.score?.homeGoals??0} × {snapshot.score?.awayGoals??0}</div><Metric label="Último evento" value={raw?.lastEventSequence??0}/><Metric label="Reconciliação" value={reconciliation.every(row=>row.ok)?"consistente":"divergente"}/></Card><Card title="Comunicação"><Metric label="Estado" value={health.connection}/><Metric label="Snapshots/s" value={health.snapshotsPerSecond}/><Metric label="Latência" value={`${health.latencyMs} ms`}/><Metric label="Jitter" value={`${health.jitterMs} ms`}/><Metric label="Lacunas" value={health.missingSnapshots+health.missingEvents}/></Card><Card title="Alertas"><Metric label="Erros" value={alerts.filter(alert=>alert.severity==="ERROR").length}/><Metric label="Avisos" value={alerts.filter(alert=>alert.severity==="WARNING").length}/><Metric label="Duplicados" value={health.duplicates}/><Metric label="Fora de ordem" value={health.outOfOrder}/></Card></div>;
}

function Statistics({raw,reconciliation}:{raw:RawNetworkSnapshot|null;reconciliation:readonly ReconciliationRow[]}){
  const teams=raw?.analytics?.teams??{}; const metrics=["possessionPercent","passesAttempted","passesCompleted","passAccuracy","progressivePasses","passesIntoFinalThird","passesIntoPenaltyArea","shots","shotsOnTarget","shotsOffTarget","shotsBlocked","goals","xG","corners","fouls","yellowCards","redCards","tackles","tacklesWon","interceptions","recoveries","duels","duelsWon","goalkeeperSaves","distanceTravelled"];
  return <><table className="stats-table"><thead><tr><th>Métrica</th>{Object.keys(teams).map(team=><th key={team}>{team}</th>)}</tr></thead><tbody>{metrics.map(metric=><tr key={metric}><td>{metric}</td>{Object.entries(teams).map(([team,report])=><td key={team}>{formatValue(report[metric])}</td>)}</tr>)}</tbody></table><h3>Reconciliação evento × oficial</h3><table className="stats-table"><tbody>{reconciliation.map(row=><tr key={`${row.teamId}-${row.metric}`} className={row.ok?"row-ok":"row-error"}><td>{row.teamId}</td><td>{row.metric}</td><td>{row.official}</td><td>{row.derived}</td><td>{row.delta}</td></tr>)}</tbody></table></>;
}

function Players({raw,snapshot,selectedId,onSelect,selected}:{raw:RawNetworkSnapshot|null;snapshot:MatchSnapshot;selectedId:string|null;onSelect:(id:string|null)=>void;selected:MatchSnapshot["players"][number]|null}){
  const report=selected&&raw?.analytics?.players?.[selected.id];
  return <div className="inspector-layout"><div className="player-list">{snapshot.players.map(player=><button className={selectedId===player.id?"active":""} onClick={()=>onSelect(player.id)} key={player.id}><i className={player.team==="HOME"?"home-dot":"away-dot"}/>{player.id}<small>{player.role}</small></button>)}</div>{selected?<div className="debug-grid"><Card title={`Estado atual — ${selected.id}`}><Metric label="Equipe / função" value={`${selected.team} · ${selected.role??"—"}`}/><Metric label="Engine (m)" value={selected.enginePosition?`${selected.enginePosition.x.toFixed(2)}, ${selected.enginePosition.y.toFixed(2)}`:"—"}/><Metric label="Render (%)" value={`${selected.x.toFixed(2)}, ${selected.y.toFixed(2)}`}/><Metric label="Velocidade" value={selected.velocity?`${Math.hypot(selected.velocity.x,selected.velocity.y).toFixed(2)} m/s`:"—"}/><Metric label="Orientação" value={selected.bodyOrientation?.toFixed(2)??"—"}/><Metric label="Ação" value={selected.action??"IDLE"}/><Metric label="Animação" value={selected.animationState??"—"}/><Metric label="Intenção" value={selected.currentIntent??"—"}/><Metric label="Alvo" value={selected.actionTargetId??"—"}/><Metric label="Destino" value={selected.targetPosition?`${selected.targetPosition.x.toFixed(1)}, ${selected.targetPosition.y.toFixed(1)}`:"—"}/><Metric label="Última decisão" value={selected.lastDecisionAt?.toFixed(2)??"—"}/><Metric label="Condição / fadiga" value={`${formatValue(selected.condition)} / ${formatValue(selected.fatigue)}`}/><Metric label="Estado corporal" value={selected.bodyState??"—"}/></Card><Card title="Relatório causal"><Metric label="Gols / assistências" value={`${formatValue(report?.goals)} / ${formatValue(report?.assists)}`}/><Metric label="Chutes" value={formatValue(report?.shots)}/><Metric label="Passes" value={`${formatValue(report?.passesCompleted)} / ${formatValue(report?.passesAttempted)}`}/><Metric label="Passes progressivos" value={formatValue(report?.progressivePasses)}/><Metric label="Conduções" value={formatValue(report?.carries)}/><Metric label="Perdas" value={formatValue(report?.possessionLosses)}/><Metric label="Desarmes" value={`${formatValue(report?.tacklesWon)} / ${formatValue(report?.tackles)}`}/><Metric label="Interceptações" value={formatValue(report?.interceptions)}/><Metric label="Recuperações" value={formatValue(report?.recoveries)}/><Metric label="Duelos" value={`${formatValue(report?.duelsWon)} / ${formatValue(report?.duels)}`}/><Metric label="Cartões" value={formatValue(report?.cards)}/><Metric label="Distância" value={report?.distanceTravelled?`${Number(report.distanceTravelled).toFixed(1)} m`:"0 m"}/></Card></div>:<p>Selecione um jogador no campo ou na lista.</p>}</div>;
}

function Possession({raw,snapshot}:{raw:RawNetworkSnapshot|null;snapshot:MatchSnapshot}){const intervals=raw?.analytics?.possessionIntervals??[];const prediction=snapshot.possessionPrediction;const active=intervals.at(-1) as {startedAt?:number;endedAt?:number}|undefined;return <div className="debug-grid"><Card title="Posse confirmada"><Metric label="Time" value={raw?.possessionTeamId??"bola livre"}/><Metric label="Controlador" value={raw?.ball.ownerId??"nenhum"}/><Metric label="Estado da bola" value={raw?.ball.state??"—"}/><Metric label="Velocidade" value={raw?`${Math.hypot(raw.ball.velocity.x,raw.ball.velocity.y).toFixed(2)} m/s`:"—"}/><Metric label="Sequências" value={intervals.length}/><Metric label="Duração recente" value={active?.startedAt!==undefined&&active?.endedAt!==undefined?`${(active.endedAt-active.startedAt).toFixed(2)} s`:"—"}/></Card><Card title="Posse provável"><Metric label="Time" value={prediction?.likelyTeamId??"disputada"}/><Metric label="Receptor" value={prediction?.likelyReceiverId??"—"}/><Metric label="Estado" value={prediction?.state??"—"}/><Metric label="Confiança" value={`${((prediction?.confidence??0)*100).toFixed(1)}%`}/><Metric label="Risco de interceptação" value={`${((prediction?.interceptionRisk??0)*100).toFixed(1)}%`}/><Metric label="Transição" value={prediction?.transitionReason??"—"}/></Card><Card title="Intervalos causais"><pre className="mini-raw">{JSON.stringify(intervals.slice(-8),null,2)}</pre></Card></div>}
function Shots({raw}:{raw:RawNetworkSnapshot|null}){const shots=(raw?.sequencedEvents??[]).filter(event=>event.type.startsWith("SHOT")||["GOAL","WOODWORK","GOALKEEPER_SAVE"].includes(event.type));return <div className="shot-list">{shots.slice().reverse().map(event=><details key={event.sequence}><summary>#{event.sequence} · {event.type} · {event.playerId??event.teamId??"—"}</summary><pre>{JSON.stringify(event,null,2)}</pre></details>)}</div>}
function EngineFront({raw,snapshot,renderedState}:{raw:RawNetworkSnapshot|null;snapshot:MatchSnapshot;renderedState:Props["renderedState"]}){if(!raw)return <p>Sem snapshot.</p>;const ballExpected={x:raw.ball.position.x/raw.pitch.length*100,y:raw.ball.position.y/raw.pitch.width*100};const ballError=Math.hypot(ballExpected.x-renderedState.ball.x,ballExpected.y-renderedState.ball.y);return <><table className="stats-table"><thead><tr><th>Entidade</th><th>Engine (m)</th><th>Recebida (%)</th><th>Renderizada (%)</th><th>Erro visual</th><th>Status / ação</th></tr></thead><tbody>{snapshot.players.map(player=>{const source=raw.players.find(item=>item.id===player.id);const rendered=renderedState.players[player.id]??player;const error=Math.hypot(player.x-rendered.x,player.y-rendered.y);const status=error<.15?"synchronized":error<2?"interpolating":"divergent";return <tr key={player.id} className={status==="divergent"?"row-error":"row-ok"}><td>{player.id}</td><td>{source?`${source.position.x.toFixed(2)}, ${source.position.y.toFixed(2)}`:"—"}</td><td>{player.x.toFixed(2)}, {player.y.toFixed(2)}</td><td>{rendered.x.toFixed(2)}, {rendered.y.toFixed(2)}</td><td>{error.toFixed(3)}%</td><td>{status} · {player.action??"IDLE"} → {player.animationState??"—"}</td></tr>})}<tr className={ballError>2?"row-error":"row-ok"}><td>BOLA</td><td>{raw.ball.position.x.toFixed(2)}, {raw.ball.position.y.toFixed(2)}, z {raw.ball.height.toFixed(2)}</td><td>{snapshot.ball.x.toFixed(2)}, {snapshot.ball.y.toFixed(2)}</td><td>{renderedState.ball.x.toFixed(2)}, {renderedState.ball.y.toFixed(2)}</td><td>{ballError.toFixed(3)}%</td><td>{ballError<.15?"synchronized":ballError<2?"interpolating":"divergent"} · {raw.ball.state}</td></tr></tbody></table><p className="hint">Captura real do renderer atualizada a cada 200 ms; atraso {Math.max(0,Date.now()-renderedState.capturedAt)} ms.</p></>}
function Synchronization({adapter,health,reconciliation,rendererFrozen,onRendererFrozen,onStep}:{adapter:MatchStateAdapter;health:CommunicationHealth;reconciliation:readonly ReconciliationRow[];rendererFrozen:boolean;onRendererFrozen:(value:boolean)=>void;onStep:()=>void}){const lifecycle=adapter.actionLifecycle();return <><div className="debug-grid"><Card title="Transporte"><Metric label="Recebidos / aceitos" value={`${health.received} / ${health.accepted}`}/><Metric label="Última sequência" value={health.lastSequence}/><Metric label="Último evento" value={health.lastEventSequence}/><Metric label="Snapshots ausentes" value={health.missingSnapshots}/><Metric label="Eventos ausentes" value={health.missingEvents}/></Card><Card title="Controles de diagnóstico"><button onClick={()=>onRendererFrozen(!rendererFrozen)}>{rendererFrozen?"Retomar renderer":"Congelar renderer"}</button><button onClick={onStep}>Avançar 1 tick da engine</button><p className="hint">O passo manual exige a engine pausada. Congelar o renderer não pausa WebSocket nem engine.</p></Card><Card title="Consistência"><Metric label="Métricas comparadas" value={reconciliation.length}/><Metric label="Divergências" value={reconciliation.filter(row=>!row.ok).length}/></Card></div><h3>Ciclo de vida das ações</h3><table className="stats-table"><thead><tr><th>Jogador</th><th>Ação</th><th>Tick</th><th>Engine</th><th>Enviado</th><th>Recebido / fila</th><th>Animação</th></tr></thead><tbody>{lifecycle.slice(-50).reverse().map((entry,index)=><tr key={`${entry.playerId}-${entry.action}-${index}`}><td>{entry.playerId}</td><td>{entry.action}</td><td>{entry.simulationTick}</td><td>{entry.engineAt}</td><td>{entry.sentAt}</td><td>{entry.receivedAt}</td><td>{entry.animation}</td></tr>)}</tbody></table></>}
function Alerts({alerts}:{alerts:readonly DebugAlert[]}){return <div className="alert-list">{alerts.length?alerts.map(alert=><div key={alert.id} className={`alert-${alert.severity.toLowerCase()}`}><b>{alert.severity} · {alert.code}</b><span>{alert.message}</span><small>snapshot #{alert.sequence}</small></div>):<p>Nenhum alerta de sincronização.</p>}</div>}
function Configuration(props:Props){const download=()=>{const blob=new Blob([props.adapter.export(props.raw)],{type:"application/json"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=`match-debug-${props.raw?.matchId??"unknown"}.json`;anchor.click();URL.revokeObjectURL(url)};return <div className="debug-grid"><Card title="Nível de debug"><select value={props.debugLevel} onChange={event=>props.onDebugLevel(event.target.value as DebugLevel)}>{["OFF","BASIC","STATISTICS","SYNCHRONIZATION","FULL"].map(value=><option key={value}>{value}</option>)}</select></Card><Card title="Retenção"><select value={props.retention} onChange={event=>props.onRetention(event.target.value as RetentionMode)}>{["rollingBuffer","importantEvents","sampled","fullDebug"].map(value=><option key={value}>{value}</option>)}</select><Metric label="Snapshots retidos" value={props.adapter.retainedSnapshots().length}/><Metric label="Eventos retidos" value={props.adapter.retainedEvents().length}/></Card><Card title="Exportação"><button onClick={download}>Baixar JSON de diagnóstico</button><p className="hint">Inclui contrato bruto, eventos, alertas e saúde do transporte.</p></Card></div>}
function HealthBadge({health}:{health:CommunicationHealth}){return <span className={`health-badge health-${health.connection.toLowerCase()}`}>{health.connection} · {health.snapshotsPerSecond} Hz · {health.latencyMs} ms</span>}
function Card({title,children}:{title:string;children:React.ReactNode}){return <article className="debug-card"><h3>{title}</h3>{children}</article>}
function Metric({label,value}:{label:string;value:unknown}){return <div className="debug-metric"><span>{label}</span><b>{value===undefined?"—":String(value)}</b></div>}
const formatClock=(seconds:number)=>`${Math.floor(seconds/60).toString().padStart(2,"0")}:${Math.floor(seconds%60).toString().padStart(2,"0")}`;
const formatValue=(value:unknown):string|number=>typeof value==="number"?(Number.isInteger(value)?value:value.toFixed(2)):typeof value==="string"?value:value==null?"—":JSON.stringify(value);
